		$(document).ready(function(){
		 $("#developer-content").hide();
		 $("#contractor-content").hide();
		 $("#consultant-content").show();
		 $("#investor-content").hide();
		 $("#share-content").hide();
		 $("#partner-content").hide();
		 
		}); 
		$(document).ready(function(){
    	  $("#developer").click(function(){
		 $("#developer-content").show();
		 $("#contractor-content").hide();
		 $("#investor-content").hide();
		 $("#consultant-content").hide();
		 $("#share-content").hide();
		 $("#partner-content").hide();
		  });
		  $("#contractor").click(function(){
		  $("#developer-content").hide();
		 $("#contractor-content").show();
		 $("#investor-content").hide();
		 $("#consultant-content").hide();
		 $("#share-content").hide();
		 $("#partner-content").hide();
		  });
		 		  	  
		 $("#investor").click(function(){
		 $("#developer-content").hide();
		 $("#contractor-content").hide();
		 $("#investor-content").show();
		 $("#consultant-content").hide();
		 $("#share-content").hide();
		 $("#partner-content").hide();
		  });
		  
		   $("#consultant").click(function(){
		 $("#developer-content").hide();
		 $("#contractor-content").hide();
		 $("#investor-content").hide();
		 $("#consultant-content").show();
		 $("#share-content").hide();
		 $("#partner-content").hide();
		  });
		  $("#share-earn").click(function(){
		 $("#developer-content").hide();
		 $("#contractor-content").hide();
		 $("#investor-content").hide();
		 $("#consultant-content").hide();
		 $("#share-content").show();
		 $("#partner-content").hide();
		  });
		  
		  $("#partner").click(function(){
		 $("#developer-content").hide();
		 $("#contractor-content").hide();
		 $("#investor-content").hide();
		 $("#consultant-content").hide();
		 $("#share-content").hide();
		 $("#partner-content").show();
		  });
		  
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").show();
		}); 
		$(document).ready(function(){
    	  $("#sugar1").click(function(){
		  $("#sugar1-content").show();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  $("#sugar2").click(function(){
		  $("#sugar1-content").hide();
		 $("#sugar2-content").show();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		 		  	  
		 $("#sugar3").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").show();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		   $("#sugar4").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").show();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		  
		  
		 $("#sugar5").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").show();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		   $("#sugar6").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").show();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		   $("#sugar7").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").show();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		   $("#sugar8").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").show();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		   $("#sugar9").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").show();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		  $("#sugar10").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").show();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  }); 
		 
		$("#sugar11").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").show();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  }); 	
		  
		  $("#sugar12").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").show();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		 $("#sugar13").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").show();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").hide();
		  });
		  
		  $("#sugar14").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").show();
		 $("#sugar15-content").hide();
		  }); 
		  
		   $("#sugar15").click(function(){
		 $("#sugar1-content").hide();
		 $("#sugar2-content").hide();
		 $("#sugar3-content").hide();
		 $("#sugar4-content").hide();
		 $("#sugar5-content").hide();
		 $("#sugar6-content").hide();
		 $("#sugar7-content").hide();
		 $("#sugar8-content").hide();
		 $("#sugar9-content").hide();
		 $("#sugar10-content").hide();
		 $("#sugar11-content").hide();
		 $("#sugar12-content").hide();
		 $("#sugar13-content").hide();
		 $("#sugar14-content").hide();
		 $("#sugar15-content").show();
		  }); 
		  
		});
		