//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateProject
    {
        public int AssociateProjectID { get; set; }
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string ProjectName { get; set; }
        public string Industry { get; set; }
        public string ProjectInquiryType { get; set; }
        public Nullable<decimal> SalesMarginExpectation { get; set; }
        public string CustomerType { get; set; }
        public string ProjectInquiryStatus { get; set; }
        public Nullable<System.DateTime> ImportantDate { get; set; }
        public Nullable<System.DateTime> InquirySubmissionDate { get; set; }
        public Nullable<System.DateTime> OfferSubmissionDate { get; set; }
        public Nullable<System.DateTime> LetterIntentReleaseDate { get; set; }
        public Nullable<System.DateTime> ContractSigningDate { get; set; }
        public Nullable<System.DateTime> FirstPaymentdate { get; set; }
        public Nullable<System.DateTime> CompletePaymentdate { get; set; }
        public Nullable<System.DateTime> ContractExecutionDate { get; set; }
        public string CollaborateWithUs { get; set; }
        public string AssociateWithi4i { get; set; }
        public string Attachment { get; set; }
        public string UserNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ReasonForDisapprove { get; set; }
        public string CurrentYear { get; set; }
        public string Status { get; set; }
        public string ContactNumber { get; set; }
        public string Capacity { get; set; }
        public string Description { get; set; }
        public string ReasonOfUnhappiness { get; set; }
        public string OfferDocument { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
