//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateRefferal
    {
        public int AssociateRefferalID { get; set; }
        public string PersonName { get; set; }
        public string ContactNumber { get; set; }
        public string ReferralEmail { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
