//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int ID { get; set; }
        public string CompID { get; set; }
        public string TypeOfCertificate { get; set; }
        public string RefNo { get; set; }
        public string Name { get; set; }
        public string IssuedBy { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Scope { get; set; }
    }
}
