//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Vision { get; set; }
        public string BusinessInterest { get; set; }
        public string WeAre { get; set; }
        public string YearOfCompReg { get; set; }
        public string TotalEmployee { get; set; }
        public string FinancialRating { get; set; }
        public string VideoProfile { get; set; }
    }
}
