//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int ConversationID { get; set; }
        public int ProjectID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Proposalfile { get; set; }
        public string Subject { get; set; }
        public string SentBy { get; set; }
    }
}
