//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentYear
    {
        public int CurrentYearID { get; set; }
        public string CurrentYear1 { get; set; }
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public string ProjectStatus { get; set; }
        public string PaymentStatus { get; set; }
    }
}
