//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageLikeAndComment
    {
        public int PImageLikeId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> ImgLikeFlag { get; set; }
        public string ImageTestimonials { get; set; }
        public Nullable<bool> CmtImgFlag { get; set; }
    }
}
