//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustrySubCategory
    {
        public int Id { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> IndusCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
