//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputQueryData
    {
        public long Id { get; set; }
        public string Attachments { get; set; }
        public string QueryText { get; set; }
        public string UQueryNum { get; set; }
        public string acion { get; set; }
        public Nullable<System.DateTime> QDate { get; set; }
        public Nullable<long> Supplier { get; set; }
        public Nullable<System.DateTime> ForwardDate { get; set; }
        public string UserNo { get; set; }
        public string QType { get; set; }
    }
}
