//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInUser
    {
        public int LinkedinUserID { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> userId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Industry { get; set; }
        public Nullable<bool> CreditM { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Approvedate { get; set; }
        public string picUrl { get; set; }
    }
}
