//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetailWorldRef
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string Industry { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> Country { get; set; }
        public string ProfilePath { get; set; }
        public string ProfileName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsLogin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<int> isDeleted { get; set; }
    }
}
