//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageDocument
    {
        public int DocumentID { get; set; }
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string DocumentType { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Industry { get; set; }
        public string Topic { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Charges { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SampleAttach { get; set; }
        public string Status { get; set; }
    }
}
