//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeDetails_RegCorpHead
    {
        public int ID { get; set; }
        public string CompID { get; set; }
        public string StreetNo { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string OfficeContactNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string PersonUndEnglish { get; set; }
        public string OfficeType { get; set; }
    }
}
