//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners_Associates
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string TypeOfPartnership { get; set; }
        public string Description { get; set; }
        public string territories { get; set; }
        public string Logo { get; set; }
        public string CompID { get; set; }
    }
}
