//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImage
    {
        public int id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> link { get; set; }
        public string ProjectCertificates { get; set; }
    }
}
