//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLikeDisLike
    {
        public int id { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> totalLike { get; set; }
        public string totalDislike { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
