//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRating
    {
        public int id { get; set; }
        public Nullable<int> projectId { get; set; }
        public string rating { get; set; }
        public string QualityRating { get; set; }
        public string UserRating { get; set; }
    }
}
