//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectContactDetail
    {
        public int ContactDetailID { get; set; }
        public int Id { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Organisation { get; set; }
        public Nullable<int> IndustriesID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
