//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLinkedInMember
    {
        public int id { get; set; }
        public string ProfileUrl { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAuthorized { get; set; }
        public System.DateTime createdOn { get; set; }
        public int ProjectId { get; set; }
    }
}
