//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImageVideoComment
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProjectImageId { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Show { get; set; }
    }
}
