//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectReview
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
        public Nullable<bool> Publish { get; set; }
        public Nullable<bool> UnPublish { get; set; }
        public Nullable<bool> AdminFlag { get; set; }
    }
}
