//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCertificate
    {
        public int CertificationID { get; set; }
        public int PromotionLibraryID { get; set; }
        public string CertificateName { get; set; }
        public string CertificateAttachment { get; set; }
    }
}
