//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionProductList
    {
        public int PromotionProductID { get; set; }
        public int PromotionLibraryID { get; set; }
        public string ProductName { get; set; }
        public string ProductBrochure { get; set; }
        public string ProductIndustry { get; set; }
        public string URSFormat { get; set; }
    }
}
