//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionLibrary
    {
        public int PromotionLibraryID { get; set; }
        public string PName { get; set; }
        public string PEmailId { get; set; }
        public string PContactNumber { get; set; }
        public string PReference { get; set; }
        public string PCompanyProfile { get; set; }
        public int IndustriesID { get; set; }
        public string ReasonForDisapproved { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
    }
}
