//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionOtherDocument
    {
        public int POtherDocumentID { get; set; }
        public int PromotionLibraryID { get; set; }
        public string OtherDocumentName { get; set; }
        public string DocumentAttachment { get; set; }
    }
}
