//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promote_Associate
    {
        public int PromoteID { get; set; }
        public Nullable<int> PromotionLibraryID { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> IndustriesID { get; set; }
    }
}
