//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string phone { get; set; }
        public string UserRole { get; set; }
        public string Company { get; set; }
        public string Password { get; set; }
        public string ProfileAttach { get; set; }
        public string PhotoAttach { get; set; }
        public string CountryName { get; set; }
        public string BusinessInterestCountry { get; set; }
        public string Products { get; set; }
        public string Region { get; set; }
        public string Industries { get; set; }
        public string ReferredBy { get; set; }
        public string Type { get; set; }
        public string RecruitmentType { get; set; }
        public string ProfileUrl { get; set; }
        public string OrgName { get; set; }
        public Nullable<bool> RecruiterFlag { get; set; }
        public string UploaderType { get; set; }
        public string OrganisationName { get; set; }
        public string BussinessUnitName { get; set; }
        public string MyCompany { get; set; }
        public string RecoveryMail { get; set; }
        public string OtherMail { get; set; }
        public string OfficialNumber { get; set; }
        public Nullable<int> ProfileLanguageID { get; set; }
    }
}
