//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentativeDocument
    {
        public int ID { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<int> ShownToRepresentative { get; set; }
        public string UploadDate { get; set; }
    }
}
