//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchImageView
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> link { get; set; }
        public string ProjectCertificates { get; set; }
        public string SearchKeyword { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string OrganizationName { get; set; }
        public string CustomerName { get; set; }
        public string ProjectName { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public string Country { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsOrganization { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsProject { get; set; }
        public Nullable<bool> IsType { get; set; }
        public Nullable<bool> IsCountry { get; set; }
        public Nullable<bool> IsYear { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public string ExcelPath { get; set; }
        public string ExcelName { get; set; }
        public Nullable<int> IsAuthorized { get; set; }
        public string DisApproveReason { get; set; }
        public Nullable<bool> IsStatus { get; set; }
        public string Status { get; set; }
        public string CustomerIndustryType { get; set; }
        public Nullable<bool> IsAdminAuthorized { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAdminUnAuthorized { get; set; }
        public string ProjectLocation { get; set; }
        public Nullable<bool> UserEditFlag { get; set; }
    }
}
