//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int ID { get; set; }
        public string CompID { get; set; }
        public string Photo { get; set; }
        public string InterviewWith { get; set; }
        public string StoryText { get; set; }
    }
}
