//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierProposal
    {
        public long Id { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string UQueryNum { get; set; }
        public string attachment { get; set; }
        public Nullable<System.DateTime> ProposalDate { get; set; }
        public Nullable<long> QueryId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> I4IForwardDate { get; set; }
        public string Deviations { get; set; }
    }
}
