//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public long Id { get; set; }
        public string Company { get; set; }
        public string ContactPersonName { get; set; }
        public string phone { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
    }
}
