//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicIndustry
    {
        public int IndustryTopicID { get; set; }
        public int Id { get; set; }
        public int IndustriesID { get; set; }
        public string Topic { get; set; }
        public int CurrencyID { get; set; }
        public decimal Price { get; set; }
        public int TimeDurationID { get; set; }
    }
}
