//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSample
    {
        public int SampleId { get; set; }
        public string UserNo { get; set; }
        public string DocumentType { get; set; }
        public int Id { get; set; }
        public string SampleAttach { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
