//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Profile
    {
        public int TrainerProfileID { get; set; }
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string UserName { get; set; }
        public string TrainerImage { get; set; }
        public string Iam { get; set; }
        public string Organisation { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public string LocatedAt { get; set; }
        public string SpeakLanguages { get; set; }
        public Nullable<bool> FluentEnglish { get; set; }
        public string IntrestedIndustries { get; set; }
        public Nullable<bool> AnswerQuery { get; set; }
        public Nullable<bool> HelthIssue { get; set; }
        public string PreferredCountry { get; set; }
        public Nullable<bool> Passport { get; set; }
        public string CompleteName { get; set; }
        public string PassportNumber { get; set; }
        public string IssuePlace { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Citizenship { get; set; }
        public string Keyword { get; set; }
        public string Topic { get; set; }
        public string TimeDuration { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
