//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerBook
    {
        public int BookTrainerID { get; set; }
        public int IndustryTopicID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> TotalTopic { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<decimal> TotalPayments { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    }
}
