//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSampleOrder
    {
        public long Id { get; set; }
        public Nullable<long> TrainerId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderHr { get; set; }
        public string OrderMin { get; set; }
        public string OrderAm { get; set; }
        public string Email { get; set; }
    }
}
