//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int UserDetailsID { get; set; }
        public string UserName { get; set; }
        public string Keywords { get; set; }
        public string LocationIP { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string EmailId { get; set; }
        public string flag { get; set; }
    }
}
