//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile_Edit
    {
        public int ID { get; set; }
        public string FinancialRating { get; set; }
        public string ISO { get; set; }
        public string OHSOS { get; set; }
        public string EmployeeNo { get; set; }
        public string Revenue { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Iso_FileName { get; set; }
        public string Iso_ExpiryDate { get; set; }
        public string Ohsos_ExpiryDate { get; set; }
        public string Ohsos_FileName { get; set; }
        public string Addres { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FinancialIssuedBy { get; set; }
    }
}
