//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideosLikeAndComment
    {
        public int PVideosId { get; set; }
        public Nullable<int> VideosId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> VideosLikeFlag { get; set; }
        public string VideosTestimonials { get; set; }
        public Nullable<bool> cmtVidFlag { get; set; }
    }
}
